.Dd May 25, 2022
.Dt BPFTUNE-SYSCTL 1
.Os
.Sh NAME
.Nm bpftune-sysctl
.Nd The sysctl tuner watches for administrator-driven sysctl settings and disables tuners that could collide with them.
.Pp
.Sh DESCRIPTION
Each tuner declares which sysctls it operates on, and if we see a sysctl setting that collides with one of our managed sysctls, the associated tuner is disabled.
.Pp
